# File: .github/workflows/workflow.yml

on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:  
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - run: |
        az group create -l westeurope -n actions-rg 
    - run: |
        az group deployment create -g actions-rg --template-file ../template.json
