# File: .github/workflows/workflow.yml
# 

on: [push]

env:
  AZURE_RESOURCE_GROUP: action-rg
  AZURE_TEMPLATE_FILE: template.json
  AZURE_PARAMETERS_FILE: params.jaon

name: AzureARMTest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:  
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - run: |
        az group create -l westeurope -n actions-rg
    - run: |
        az group deployment create -n test -g actions-rg --template-file template.json --parameters params.json
      working-directory: arm-templates