# File: .github/workflows/workflow.yml
# 

on: [push]

env:
  AZURE_RESOURCE_GROUP: action-rg2
  ARM_TEMPLATE_FILE: template.json
  ARM_PARAMETERS_FILE: params.json
  AZURE_KEYVAULT: "/subscriptions/6f66105f-d352-482f-970b-a1d2a478fb64/resourceGroups/KeyVaultRG/providers/Microsoft.KeyVault/vaults/pelithneKeyVault"

name: AzureARMDeployment

jobs:
  build-infra:
    runs-on: ubuntu-latest
    steps: 
    # Azure login   
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Create Resource Group
    - run: az group create -l westeurope -n ${{ env.AZURE_RESOURCE_GROUP }}
    # Check out code and create AKS cluster using ARM templates
    - uses: actions/checkout@v1 
    - run: az group deployment create -n test -g ${{ env.AZURE_RESOURCE_GROUP }} --template-file ${{ env.ARM_TEMPLATE_FILE }} --parameters params.json
      working-directory: ./arm-templates
